name: my_attendance
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.2.2
  mobile_scanner: ^3.3.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  qr_flutter: ^4.0.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  excel: ^2.0.6
  camera: ^0.10.5+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - asset/logo.png
    # <-- Make sure this image exists in your asset folder

flutter_icons:
  android: true
  ios: true
  image_path: "asset/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: asset/logo.png
  android: true
  ios: true
  web: false
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
